name: Deploy Auth Lambda

on:
  push:
    paths:
      - 'lambda-auth/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Archive lambda
        run: |
          cd lambda-auth
          npm ci --omit=dev
          zip -r ../lambda-auth.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Update Lambda code
        run: |
          aws lambda update-function-code --function-name autosnsflow-auth --zip-file fileb://lambda-auth.zip
